FROM python:3.11-slim

WORKDIR /app

COPY student-1/requirments.txt .


#will have to make it so that all the "requirements.txt" relate to the document in /student-1 NOT 
# in each file directory (i have have only done this so i can get docker to work) 

RUN pip install --no-cache-dir -r requirements.txt

COPY prompts/service ./service

EXPOSE 5001

CMD ["python", "backend/app.py"]


