# this will be to communicate with the main app.py. 
# connecting the app.py in the backend part of stuendet-1 to the frontend of the shared parts of the work


FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/app.py .
COPY backend/init_db.py .

RUN python backend/init_db.py

EXPOSE 5002

CMD ["python", "backend/app.py"]