FROM nginx:alpine

WORKDIR /student-1

COPY *.html /usr/share/nginx/html/

# From lab 7 
# COPY css/ /usr/share/nginx/html/css/

# COPY where mcp-server/server.py is located
# COPY ../server.py 

EXPOSE 80