FROM python:3.11-slim


WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# COPY app.py .
COPY . .



# matches app.py now, when originally working it was 5002 but this shouldnt break the application
EXPOSE 5001

CMD ["python", "app.py"]